import {
  AlertCircle,
  AlertTriangle,
  Anchor,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Book,
  BookOpen,
  Bookmark,
  Calendar,
  Check,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  Clock,
  Code,
  Compass,
  Crown,
  Dumbbell,
  Edit,
  FileText,
  GitBranch,
  Globe,
  Hash,
  HelpCircle,
  Home,
  Info,
  Landmark,
  Lightbulb,
  List,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  MessageCircleQuestion,
  MessageSquareWarning,
  Moon,
  Mountain,
  Orbit,
  PauseCircle,
  PenTool,
  PlayCircle,
  Puzzle,
  RotateCcw,
  Rss,
  ScrollText,
  Settings,
  Shield,
  ShieldAlert,
  Sparkles,
  Sun,
  Swords,
  Tag,
  Tags,
  User,
  Users,
  X,
  XCircle,
} from 'lucide-react'
import type { LucideProps } from 'lucide-react'

const iconMap = {
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  anchor: Anchor,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  book: Book,
  'book-open': BookOpen,
  bookmark: Bookmark,
  calendar: Calendar,
  check: Check,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'check-square': CheckSquare,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-help': CircleHelp,
  clock: Clock,
  code: Code,
  compass: Compass,
  crown: Crown,
  dumbbell: Dumbbell,
  edit: Edit,
  'file-text': FileText,
  'git-branch': GitBranch,
  github: GitBranch, // Using GitBranch as GitHub brand icon is deprecated
  globe: Globe,
  hash: Hash,
  'help-circle': HelpCircle,
  home: Home,
  info: Info,
  landmark: Landmark,
  lightbulb: Lightbulb,
  list: List,
  mail: Mail,
  map: Map,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  'message-circle-question': MessageCircleQuestion,
  'message-square-warning': MessageSquareWarning,
  moon: Moon,
  mountain: Mountain,
  orbit: Orbit,
  'pause-circle': PauseCircle,
  'pen-tool': PenTool,
  'play-circle': PlayCircle,
  puzzle: Puzzle,
  'rotate-ccw': RotateCcw,
  rss: Rss,
  scroll: ScrollText,
  settings: Settings,
  shield: Shield,
  'shield-alert': ShieldAlert,
  sparkles: Sparkles,
  sun: Sun,
  swords: Swords,
  tag: Tag,
  tags: Tags,
  user: User,
  users: Users,
  x: X,
  'x-circle': XCircle,
} as const

type IconName = keyof typeof iconMap

interface IconProps extends Omit<LucideProps, 'ref'> {
  name: IconName | `lucide:${IconName}`
}

export function Icon({ name, ...props }: IconProps) {
  // Remove 'lucide:' prefix if present
  const iconName = name.startsWith('lucide:')
    ? (name.slice(7) as IconName)
    : (name as IconName)

  const IconComponent = iconMap[iconName]

  if (!IconComponent) {
    console.warn(`Icon "${iconName}" not found`)
    return null
  }

  return <IconComponent {...props} />
}
